package responses

type IndividualCustomerCollection struct {
	D struct {
		Results []struct {
			Metadata struct {
				URI  string `json:"uri"`
				Type string `json:"type"`
				Etag string `json:"etag"`
			} `json:"__metadata"`
			ObjectID                          string `json:"ObjectID"`
			CustomerID                        string `json:"CustomerID"`
			UUID                              string `json:"UUID"`
			ExternalID                        string `json:"ExternalID"`
			ExternalSystem                    string `json:"ExternalSystem"`
			RoleCode                          string `json:"RoleCode"`
			RoleCodeText                      string `json:"RoleCodeText"`
			LifeCycleStatusCode               string `json:"LifeCycleStatusCode"`
			LifeCycleStatusCodeText           string `json:"LifeCycleStatusCodeText"`
			CustomerABCClassificationCode     string `json:"CustomerABCClassificationCode"`
			CustomerABCClassificationCodeText string `json:"CustomerABCClassificationCodeText"`
			ContactPermissionCode             string `json:"ContactPermissionCode"`
			ContactPermissionCodeText         string `json:"ContactPermissionCodeText"`
			TitleCode                         string `json:"TitleCode"`
			TitleCodeText                     string `json:"TitleCodeText"`
			AcademicTitleCode                 string `json:"AcademicTitleCode"`
			AcademicTitleCodeText             string `json:"AcademicTitleCodeText"`
			FirstName                         string `json:"FirstName"`
			MiddleName                        string `json:"MiddleName"`
			LastName                          string `json:"LastName"`
			AdditionalLastName                string `json:"AdditionalLastName"`
			Initials                          string `json:"Initials"`
			NickName                          string `json:"NickName"`
			GenderCode                        string `json:"GenderCode"`
			GenderCodeText                    string `json:"GenderCodeText"`
			NamePrefixCode                    string `json:"NamePrefixCode"`
			NamePrefixCodeText                string `json:"NamePrefixCodeText"`
			MaritalStatusCode                 string `json:"MaritalStatusCode"`
			MaritalStatusCodeText             string `json:"MaritalStatusCodeText"`
			LanguageCode                      string `json:"LanguageCode"`
			LanguageCodeText                  string `json:"LanguageCodeText"`
			BirthName                         string `json:"BirthName"`
			BirthDate                         string `json:"BirthDate"`
			NationalityCountryCode            string `json:"NationalityCountryCode"`
			NationalityCountryCodeText        string `json:"NationalityCountryCodeText"`
			ProfessionCode                    string `json:"ProfessionCode"`
			ProfessionCodeText                string `json:"ProfessionCodeText"`
			FormattedName                     string `json:"FormattedName"`
			FormattedPostalAddressDescription string `json:"FormattedPostalAddressDescription"`
			CountryCode                       string `json:"CountryCode"`
			CountryCodeText                   string `json:"CountryCodeText"`
			StateCode                         string `json:"StateCode"`
			StateCodeText                     string `json:"StateCodeText"`
			CareOfName                        string `json:"CareOfName"`
			AddressLine1                      string `json:"AddressLine1"`
			AddressLine2                      string `json:"AddressLine2"`
			HouseNumber                       string `json:"HouseNumber"`
			AdditionalHouseNumber             string `json:"AdditionalHouseNumber"`
			Street                            string `json:"Street"`
			AddressLine4                      string `json:"AddressLine4"`
			AddressLine5                      string `json:"AddressLine5"`
			District                          string `json:"District"`
			City                              string `json:"City"`
			DifferentCity                     string `json:"DifferentCity"`
			StreetPostalCode                  string `json:"StreetPostalCode"`
			County                            string `json:"County"`
			POBoxIndicator                    bool   `json:"POBoxIndicator"`
			POBox                             string `json:"POBox"`
			POBoxPostalCode                   string `json:"POBoxPostalCode"`
			POBoxDeviatingCountryCode         string `json:"POBoxDeviatingCountryCode"`
			POBoxDeviatingCountryCodeText     string `json:"POBoxDeviatingCountryCodeText"`
			POBoxDeviatingStateCode           string `json:"POBoxDeviatingStateCode"`
			POBoxDeviatingStateCodeText       string `json:"POBoxDeviatingStateCodeText"`
			POBoxDeviatingCity                string `json:"POBoxDeviatingCity"`
			TimeZoneCode                      string `json:"TimeZoneCode"`
			TimeZoneCodeText                  string `json:"TimeZoneCodeText"`
			TaxJurisdictionCode               string `json:"TaxJurisdictionCode"`
			TaxJurisdictionCodeText           string `json:"TaxJurisdictionCodeText"`
			Building                          string `json:"Building"`
			Floor                             string `json:"Floor"`
			Room                              string `json:"Room"`
			Phone                             string `json:"Phone"`
			NormalisedPhone                   string `json:"NormalisedPhone"`
			Mobile                            string `json:"Mobile"`
			NormalisedMobile                  string `json:"NormalisedMobile"`
			Fax                               string `json:"Fax"`
			Email                             string `json:"Email"`
			EmailInvalidIndicator             bool   `json:"EmailInvalidIndicator"`
			WebSite                           string `json:"WebSite"`
			BestReachedByCode                 string `json:"BestReachedByCode"`
			BestReachedByCodeText             string `json:"BestReachedByCodeText"`
			OrderBlockingReasonCode           string `json:"OrderBlockingReasonCode"`
			OrderBlockingReasonCodeText       string `json:"OrderBlockingReasonCodeText"`
			DeliveryBlockingReasonCode        string `json:"DeliveryBlockingReasonCode"`
			DeliveryBlockingReasonCodeText    string `json:"DeliveryBlockingReasonCodeText"`
			BillingBlockingReasonCode         string `json:"BillingBlockingReasonCode"`
			BillingBlockingReasonCodeText     string `json:"BillingBlockingReasonCodeText"`
			SalesSupportBlockingIndicator     bool   `json:"SalesSupportBlockingIndicator"`
			RecommendedVisitingFrequency      string `json:"RecommendedVisitingFrequency"`
			VisitDuration                     string `json:"VisitDuration"`
			LastVisitingDate                  string `json:"LastVisitingDate"`
			NextVisitingDate                  string `json:"NextVisitingDate"`
			LatestRecommendedVisitingDate     string `json:"LatestRecommendedVisitingDate"`
			OwnerID                           string `json:"OwnerID"`
			OwnerUUID                         string `json:"OwnerUUID"`
			CreationOn                        string `json:"CreationOn"`
			CreatedBy                         string `json:"CreatedBy"`
			CreatedByIdentityUUID             string `json:"CreatedByIdentityUUID"`
			ChangedOn                         string `json:"ChangedOn"`
			ChangedBy                         string `json:"ChangedBy"`
			ChangedByIdentityUUID             string `json:"ChangedByIdentityUUID"`
			EntityLastChangedOn               string `json:"EntityLastChangedOn"`
			ETag                              string `json:"ETag"`
			Mul1                              string `json:"mul1"`
			IndividualCustomerAddress         struct {
				Deferred struct {
					URI string `json:"uri"`
				} `json:"__deferred"`
			} `json:"IndividualCustomerAddress"`
		} `json:"results"`
	} `json:"d"`
}
