package responses

type ToCorporateAccount struct {
	D struct {
		Results struct {
			Metadata struct {
				URI  string `json:"uri"`
				Type string `json:"type"`
				Etag string `json:"etag"`
			} `json:"__metadata"`
			ObjectID                          string `json:"ObjectID"`
			AccountID                         string `json:"AccountID"`
			UUID                              string `json:"UUID"`
			ExternalID                        string `json:"ExternalID"`
			ExternalSystem                    string `json:"ExternalSystem"`
			RoleCode                          string `json:"RoleCode"`
			RoleCodeText                      string `json:"RoleCodeText"`
			LifeCycleStatusCode               string `json:"LifeCycleStatusCode"`
			LifeCycleStatusCodeText           string `json:"LifeCycleStatusCodeText"`
			DunsId                            string `json:"DUNSID"`
			LegalFormCode                     string `json:"LegalFormCode"`
			LegalFormCodeText                 string `json:"LegalFormCodeText"`
			CustomerABCClassificationCode     string `json:"CustomerABCClassificationCode"`
			CustomerABCClassificationCodeText string `json:"CustomerABCClassificationCodeText"`
			NielsenRegionCode                 string `json:"NielsenRegionCode"`
			NielsenRegionCodeText             string `json:"NielsenRegionCodeText"`
			IndustrialSectorCode              string `json:"IndustrialSectorCode"`
			IndustrialSectorCodeText          string `json:"IndustrialSectorCodeText"`
			ContactPermissionCode             string `json:"ContactPermissionCode"`
			ContactPermissionCodeText         string `json:"ContactPermissionCodeText"`
			BusinessPartnerFormattedName      string `json:"BusinessPartnerFormattedName"`
			Name                              string `json:"Name"`
			AdditionalName                    string `json:"AdditionalName"`
			AdditionalName2                   string `json:"AdditionalName2"`
			AdditionalName3                   string `json:"AdditionalName3"`
			CurrentDefaultAddressUUID         string `json:"CurrentDefaultAddressUUID"`
			FormattedPostalAddressDescription string `json:"FormattedPostalAddressDescription"`
			CountryCode                       string `json:"CountryCode"`
			CountryCodeText                   string `json:"CountryCodeText"`
			StateCode                         string `json:"StateCode"`
			StateCodeText                     string `json:"StateCodeText"`
			CareOfName                        string `json:"CareOfName"`
			AddressLine1                      string `json:"AddressLine1"`
			AddressLine2                      string `json:"AddressLine2"`
			HouseNumber                       string `json:"HouseNumber"`
			AdditionalHouseNumber             string `json:"AdditionalHouseNumber"`
			Street                            string `json:"Street"`
			AddressLine4                      string `json:"AddressLine4"`
			AddressLine5                      string `json:"AddressLine5"`
			District                          string `json:"District"`
			City                              string `json:"City"`
			DifferentCity                     string `json:"DifferentCity"`
			StreetPostalCode                  string `json:"StreetPostalCode"`
			County                            string `json:"County"`
			CompanyPostalCode                 string `json:"CompanyPostalCode"`
			POBoxIndicator                    bool   `json:"POBoxIndicator"`
			POBox                             string `json:"POBox"`
			POBoxPostalCode                   string `json:"POBoxPostalCode"`
			POBoxDeviatingCountryCode         string `json:"POBoxDeviatingCountryCode"`
			POBoxDeviatingCountryCodeText     string `json:"POBoxDeviatingCountryCodeText"`
			POBoxDeviatingRegionCode          string `json:"POBoxDeviatingRegionCode"`
			POBoxDeviatingRegionCodeText      string `json:"POBoxDeviatingRegionCodeText"`
			POBoxDeviatingCity                string `json:"POBoxDeviatingCity"`
			TimeZoneCode                      string `json:"TimeZoneCode"`
			TimeZoneCodeText                  string `json:"TimeZoneCodeText"`
			Building                          string `json:"Building"`
			Floor                             string `json:"Floor"`
			Room                              string `json:"Room"`
			Phone                             string `json:"Phone"`
			NormalisedPhone                   string `json:"NormalisedPhone"`
			Mobile                            string `json:"Mobile"`
			NormalisedMobile                  string `json:"NormalisedMobile"`
			Fax                               string `json:"Fax"`
			Email                             string `json:"Email"`
			WebSite                           string `json:"WebSite"`
			LanguageCode                      string `json:"LanguageCode"`
			LanguageCodeText                  string `json:"LanguageCodeText"`
			BestReachedByCode                 string `json:"BestReachedByCode"`
			BestReachedByCodeText             string `json:"BestReachedByCodeText"`
			OrderBlockingReasonCode           string `json:"OrderBlockingReasonCode"`
			OrderBlockingReasonCodeText       string `json:"OrderBlockingReasonCodeText"`
			DeliveryBlockingReasonCode        string `json:"DeliveryBlockingReasonCode"`
			DeliveryBlockingReasonCodeText    string `json:"DeliveryBlockingReasonCodeText"`
			BillingBlockingReasonCode         string `json:"BillingBlockingReasonCode"`
			BillingBlockingReasonCodeText     string `json:"BillingBlockingReasonCodeText"`
			SalesSupportBlockingIndicator     bool   `json:"SalesSupportBlockingIndicator"`
			LegalCompetenceIndicator          bool   `json:"LegalCompetenceIndicator"`
			RecommendedVisitingFrequency      string `json:"RecommendedVisitingFrequency"`
			VisitDuration                     string `json:"VisitDuration"`
			LastVisitingDate                  string `json:"LastVisitingDate"`
			NextVisitingDate                  string `json:"NextVisitingDate"`
			LatestRecommendedVisitingDate     string `json:"LatestRecommendedVisitingDate"`
			OwnerID                           string `json:"OwnerID"`
			OwnerUUID                         string `json:"OwnerUUID"`
			ParentAccountID                   string `json:"ParentAccountID"`
			CreationOn                        string `json:"CreationOn"`
			CreatedBy                         string `json:"CreatedBy"`
			CreatedByIdentityUUID             string `json:"CreatedByIdentityUUID"`
			ChangedOn                         string `json:"ChangedOn"`
			ChangedBy                         string `json:"ChangedBy"`
			ChangedByIdentityUUID             string `json:"ChangedByIdentityUUID"`
			EntityLastChangedOn               string `json:"EntityLastChangedOn"`
			ETag                              string `json:"ETag"`
			Mul1                              string `json:"mul1"`
		} `json:"results"`
	} `json:"d"`
}
